### ISSUE TITLE
Find a way to use Ansible template validation mecanism

### ISSUE THREAD

**Issue by cans** [cans/nginx-site-manage#1]
It would be nice to leverage Ansible's template validation.

## Issue

Sadly the simple command below won't work:

```yaml
- template:
     # ...
     validate: nginx -t %s
```
The reason being that the files we produce only contains the vhost sub section of the configuration:
```
server {
   ...
}
```
Whereas a valid configuration requires to nest it in a `http` section:
```
http {

    server {
       ...
    }
}
```
So we'd need a way to wrap the generated configuration file with that or use a file like:
```
http {
    // possibly requires a minimal set of configuration directives.
    include {{nginxsites_available_dir}}/{{ item.site_name }} ;
}
```
Sadly _"too clever"_ shell commands are not allowed as validation command according the documentation. Could not come up with something functional yet, not without uploading a dedicated "tool" to the target machine, beforehand [1]. Though I haven't taken the time to actually try anything yet.

### With some external a tool

Push a script like `nginx-template-validate.sh`:
```shell
#!/bin/sh
template_to_validate="${1}"
test_config_file="$(mktemp -d nginx-site-manage-validate-XXXXXX)/nginx.conf"
cat > "${test_config_file}" <<EOF
http {
    include ${template_to_validate} ;
}
EOF
nginx -t "${test_config_file}"
```
Then use something like:
```yaml
- copy:
    mode: "0700"
    src: "nginx-template-validate.sh"
    dest: " /path/to/nginx-template-validate.sh"
    state: present

- template:
     # ...
     validate: /path/to/nginx-template-validate.sh %s
```
### Turn the above script into a smart command `validate` would accept.

Maybe by using a cleverly crafted `/bin/sh -c "..."` command.
